# ============================================================
# lib/session_memory.py — Short-Term Conversation Memory
# ============================================================
# Stores the last N messages per session so the LLM can answer
# follow-up questions that refer back to previous results.
#
# WITHOUT THIS:
#   User: "What are the top 5 countries by session count?"
#   AI:   "Brazil 45%, USA 20%, Germany 10%, ..."
#   User: "Now filter that to just European ones"
#   AI:   ??? (has no idea what "that" refers to)
#
# WITH THIS:
#   The second query includes the conversation history:
#     "[Context] User previously asked: top countries by sessions
#      [Context] AI answered: Brazil 45%, Germany 10%, ..."
#   The LLM understands "that" = the country/session query,
#   and "European" = add a filter for Europe.
#
# DESIGN:
# ────────
# Simple in-memory dict: session_id → deque of last MAX_TURNS messages.
# No persistence — cleared when the server restarts or when the
# frontend starts a new session (new tab = new session_id).
#
# Each message in the deque:
#   { "role": "user" | "assistant", "content": str, "timestamp": float }
#
# The session_id is generated by the frontend on page load (random UUID)
# and sent with every query request. If no session_id is provided,
# the query runs in stateless mode (original behavior).
#
# MEMORY SIZE:
# ────────────
# We keep the last MAX_TURNS exchanges. Each exchange = one user
# message + one assistant response summary.
# At ~200 chars per message, 10 turns = ~2,000 chars ≈ ~500 tokens.
# Small enough to fit comfortably in the 8192-token context window.
# ============================================================

import time
import logging
from collections import deque

logger = logging.getLogger(__name__)

# How many conversation turns (user + assistant pairs) to remember.
# Each turn is ~200-500 chars. 10 turns ≈ 500 tokens.
MAX_TURNS = 10

# How long an inactive session lives before being garbage-collected.
# 2 hours — covers a long work session without leaking memory.
SESSION_TTL = 7200  # seconds

# ── In-memory store ───────────────────────────────────────────
# { session_id: { "messages": deque, "last_active": float } }
_sessions: dict[str, dict] = {}


def _gc() -> None:
    """
    Garbage-collects sessions that have been idle longer than SESSION_TTL.
    Called on every write to keep memory bounded.
    """
    cutoff  = time.monotonic() - SESSION_TTL
    expired = [sid for sid, s in _sessions.items() if s["last_active"] < cutoff]
    for sid in expired:
        del _sessions[sid]
    if expired:
        logger.debug(f"[session_memory] GC: removed {len(expired)} idle sessions")


def add_turn(
    session_id: str,
    question:   str,
    answer:     str,
) -> None:
    """
    Records one completed exchange (user question + AI answer).

    Call this after a successful /api/query response so future
    queries in the same session have context.

    Args:
        session_id: Opaque string from the frontend (UUID).
        question:   The user's original question.
        answer:     A short summary of what was returned
                    (resultLabel + count, not the full data).
    """
    if not session_id:
        return

    _gc()

    if session_id not in _sessions:
        _sessions[session_id] = {
            "messages":    deque(maxlen=MAX_TURNS * 2),  # 2 messages per turn
            "last_active": time.monotonic(),
        }

    session = _sessions[session_id]
    session["messages"].append({"role": "user",      "content": question})
    session["messages"].append({"role": "assistant",  "content": answer})
    session["last_active"] = time.monotonic()

    logger.debug(
        f"[session_memory] Session {session_id[:8]}: "
        f"{len(session['messages'])} messages stored"
    )


def get_context_text(session_id: str) -> str:
    """
    Returns the conversation history as a formatted text block
    to inject into the LLM's user message.

    Returns "" if there is no history (new session or stateless mode).

    Format:
        ─────────────────────
        CONVERSATION CONTEXT (previous exchanges in this session):
        User: What are the top 5 countries by session count?
        AI: Returned 5 results — 'Top Countries by Session Count'
             (Brazil 45, USA 20, Germany 12, UK 8, France 6)
        User: Now show only European countries
        ─────────────────────
    """
    if not session_id or session_id not in _sessions:
        return ""

    session  = _sessions[session_id]
    messages = list(session["messages"])

    if not messages:
        return ""

    lines = [
        "─────────────────────────────────────────────────────────────",
        "CONVERSATION CONTEXT (refer to this if the question contains",
        "'that', 'those', 'same', 'also', 'filter', 'compare', etc.):",
        "─────────────────────────────────────────────────────────────",
    ]

    for msg in messages:
        role    = "User" if msg["role"] == "user" else "AI"
        content = msg["content"][:300]   # cap each message to 300 chars
        lines.append(f"{role}: {content}")

    lines.append("─────────────────────────────────────────────────────────────")
    lines.append("")

    return "\n".join(lines)


def clear_session(session_id: str) -> None:
    """Clears history for one session. Called when user clicks 'New Chat'."""
    if session_id in _sessions:
        del _sessions[session_id]


def active_session_count() -> int:
    """Returns the number of active (non-expired) sessions."""
    _gc()
    return len(_sessions)
